version: '3.1'
services:
  app:
    build: .
    environment:
      - FILE_NAME=ports.json
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: redis:7.0.5
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network: